services:
  hub:
    image: selenium/hub:4.27.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.27.0
    shm_size: 2g
    depends_on:
      - hub
    deploy:
      replicas: 0
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4

  firefox:
    image: selenium/node-firefox:4.27.0
    shm_size: 2g
    depends_on:
      - hub
    deploy:
      replicas: 0
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4

  vendor-portal:
    image: kingabhisha/selenium-docker-runnerfile
    depends_on:
    - chrome
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - THREAD_COUNT=3
    - TEST_SUITE=vendor-portal.xml
    volumes:
    - "D:/Project/selenium-docker-master/selenium-docker-master/03-automation-framework/selenium-docker/target/docker-resources/test-suites:/home/selenium-docker/test-suites"
    - "D:/Project/selenium-docker-master/selenium-docker-master/03-automation-framework/selenium-docker/test-output-results/vendor-portal:/home/selenium-docker/test-output"

  flight-reservation:
    image: kingabhisha/selenium-docker-runnerfile
    depends_on:
    - firefox
    environment:
    - BROWSER=firefox
    - HUB_HOST=hub
    - THREAD_COUNT=4
    - TEST_SUITE=flight-reservation.xml
    volumes:
    - "D:/Project/selenium-docker-master/selenium-docker-master/03-automation-framework/selenium-docker/target/docker-resources/test-suites:/home/selenium-docker/test-suites"
    - "D:/Project/selenium-docker-master/selenium-docker-master/03-automation-framework/selenium-docker/test-output-results/flight-reservation:/home/selenium-docker/test-output"