services:
  vendor-portal:
    image: kingabhisha/selenium-docker-runnerfile
    environment:
    - BROWSER
    - HUB_HOST=hub
    - THREAD_COUNT=3
    - TEST_SUITE=vendor-portal.xml
    volumes:
    - "D:/Project/selenium-docker-master/selenium-docker-master/03-automation-framework/selenium-docker/target/docker-resources/test-suites:/home/selenium-docker/test-suites"
    - "D:/Project/selenium-docker-master/selenium-docker-master/03-automation-framework/selenium-docker/test-output-results/vendor-portal:/home/selenium-docker/test-output"

  flight-reservation:
    image: kingabhisha/selenium-docker-runnerfile
    environment:
    - BROWSER
    - HUB_HOST=hub
    - THREAD_COUNT=4
    - TEST_SUITE=flight-reservation.xml
    volumes:
    - "D:/Project/selenium-docker-master/selenium-docker-master/03-automation-framework/selenium-docker/target/docker-resources/test-suites:/home/selenium-docker/test-suites"
    - "D:/Project/selenium-docker-master/selenium-docker-master/03-automation-framework/selenium-docker/test-output-results/flight-reservation:/home/selenium-docker/test-output"